### ISSUE TITLE
Window sizing Problem with Arethusa widget

### ISSUE THREAD

**Issue by TDBuck** [perseids-project/GardenerPrototype#1]
for some themes (Leap-year and Hacker) the widget loads in too small, but will slowly get bigger if you keep switching between trees. 
For most other themes, the window will load, but after switching between trees with "cut" off the bottom of the window. 
resizing the window always results in a duplicate of the window appearing below it.

**Comment by balmas** [comment]
@TDBuck is there more you want me to do with this one? Or are have you settled on a theme that it works okay in?

**Comment by TDBuck** [comment]
we still have the "cut" problem, were the window will create that white space that covers part of the tree. the resizing issues hasn't been a problem since the navbar, since the window is now locked at a specific size. The cutoff problem seems to happen with each theme, to various degrees. It often only shows up after switching between trees.

**Comment by balmas** [comment]
@TDBuck can you take a look now to see what you think? We end up with a longer box than we need for the tree, but I think nothing is getting cutoff ...

**Comment by TDBuck** [comment]
@balmas  I'm not sure what you mean by a longer box. It looks smaller than the box we had before. But it also looks like the whitespace isn't showing up, so I think this is all good.

**Comment by balmas** [comment]
ok, I think you get the longer box when you navigate sentences, but I'll close this
