### ISSUE TITLE
Nav Bar for the Arethusa widget

### ISSUE THREAD

**Issue by TDBuck** [perseids-project/GardenerPrototype#2]
Currently you can navigate with the hotkeys, but a real navbar built into the widget would be idea for ease of use.

**Comment by TDBuck** [comment]
When I tried to rebuild the site with the new changes, the version on github page no longer loads treebanks, though the jekall-hosted local one works fine.

**Comment by balmas** [comment]
ah this might be because the aux confs request is being blocked because it's over http not https. I might have missed that change in the new config. I just updated the tbpub.json, lets see if it fixes it.

**Comment by balmas** [comment]
(It looks like you'll need to rebuild and commit the docs folder to test ... isn't GH pages supposed to be able to rebuild jekyll sites dynamically though?)

**Comment by TDBuck** [comment]
I also thought GH pages was supposed to rebuild the site. But then I noticed the github version of the site did not have the nvabar, so I rebuilt it locally. I can rebuild it locally again to test.

**Comment by balmas** [comment]
I suspect it's because you have the repository setup to serve GH pages from the docs directory. Maybe if you change it to the root and remove the docs directory it will build it itself.

**Comment by TDBuck** [comment]
it looks like that worked to help it load the arethusa logo, but it still fails to load the tagsets. It looks like one of the error messages says something is still being blocked bc its over http.

**Comment by TDBuck** [comment]
So after doing some reading, I've found a few things. the first is that GH pages doesn't support the jekyll-assets gem by default, so it doesn't use it to build the site, which is causing a whole mess of problems. The solutions I could find all said, build locally and push the results back to github, or to switch to a different platform. 
Another thing, the Jekyll 3.3 update last fall apparently set it up so that Jekyll ignores vendor folders. So this might be the reason behind lots of the smaller non-fatal errors that come up when the page loads. I could just rename the directory, but I didn't want to mess with it without you knowing, since you probably would need to make some changes to the widget. 

I will keep looking to see if there is another solution that doesn't involve forcing people to build locally. But it might be the only readily available solution.

**Comment by balmas** [comment]
ok let's proceed with the local build and push solution for now then.

**Comment by balmas** [comment]
@TDBuck are you happy with the nav bar?

**Comment by TDBuck** [comment]
@balmas I'm happy with the current nav bar.

**Comment by balmas** [comment]
super! closing this then :-)
